#!/bin/bash

# Tags should have this format:
#   {RT MAJOR}.{RT MINOR}[.{RT_PATCH}]-{IMAGE_TYPE}[_{FEATURE}[_{FEATURE}...]]
# For example:
#   4.4.5-base_developer_no-smime

PATCH=$(echo $IMAGE_NAME | cut --fields=1 --delimiter='-' | cut --fields=3 --delimiter='.')
FEATURE_FLAGS=$(echo $IMAGE_NAME | cut --fields=2- --delimiter='_' | tr '_' ' ')

BUILD_ARGS=""

[ ! -z "$PATCH" ] && BUILD_ARGS="$BUILD_ARGS --build-arg PATCH=$PATCH"

for FLAG in $FEATURE_FLAGS
do
    PREFIX=$(echo $FLAG | cut --fields=1 --delimiter='-')

    if [ "x$PREFIX" = "xdb" ]
    then
        FEATURE=DB_TYPE
        BUILD=$(echo $FLAG | cut --fields=2 --delimiter='-')
    elif [ "x$PREFIX" = "xno" ]
    then
        FEATURE=$(echo $FLAG | cut --fields=2 --delimiter='-')
        BUILD=disable
    else
        FEATURE=$FLAG
        BUILD=enable
    fi

    BUILD_ARGS="$BUILD_ARGS --build-arg ${FEATURE^^}=$BUILD"
done

docker build $BUILD_ARGS -f $DOCKERFILE_PATH -t $IMAGE_NAME .
